//#region General Activities
export const SET_ALL_GENERAL_ACTIVITY = "SET_ALL_GENERAL_ACTIVITY";
export const ADD_GENERAL_ACTIVITY = "ADD_GENERAL_ACTIVITY";
export const REMOVE_GENERAL_ACTIVITY = "REMOVE_GENERAL_ACTIVITY";
export const UPDATE_GENERAL_ACTIVITY = "UPDATE_GENERAL_ACTIVITY";
export const RESET_GENERAL_ACTIVITY = "RESET_GENERAL_ACTIVITY";
export const END_GENERAL_ACTIVITY = "END_GENERAL_ACTIVITY";
//#endregion

//#region User
export const GET_ACTIVE_USER  = "GET_ACTIVE_USER";
//#endregion